spring:
  cloud:
    gcp:
      credentials:
        location: classpath:test-houses96-firebase-adminsdk-qlv0i-e53264f362.json
      project-id: test-houses96
  security:
    user:
      name: admin
      password: admin
